# -*- coding: utf-8 -*-
"""delete/view.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FfBb9gPgXsgHgp3sUUxydzg3G13_o7ML
"""

class node:
  def__init__(self,data):
    self.data=data
    self.next=None

class Linkedlist:
  def__init__(self):
    self.start=None
#delete first node
  def deletefirst(self):
    if self.start=None:
      break
    else:
      self.start=self.start.next  
#view list
   def viewlist(self):
     if self.start==None:
       break
     else:
       temp=self.start
       while temp!=None:
         print(temp.data,end=' ')
          temp=temp.next

